# Generated by Django 6.0.6 on 2026-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='data_finalizarii',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='finalizat',
            field=models.BooleanField(default=False),
        ),
    ]
